"""add user.plan, analysis.share_token, waitlist table

Revision ID: b1a724e6e6d2
Revises: 19815e79e548
Create Date: 2026-07-18 11:20:41.283629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a724e6e6d2'
down_revision: Union[str, Sequence[str], None] = '19815e79e548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    op.add_column('scene_analyses', sa.Column('share_token', sa.String(length=48), nullable=True))
    # NOTE: autogenerate also proposed altering analysis_result JSONB -> JSON.
    # That was pre-existing drift in the local dev DB, not part of this change —
    # the baseline migration already creates the column as JSON. Dropped.
    op.create_index(op.f('ix_scene_analyses_share_token'), 'scene_analyses', ['share_token'], unique=True)
    op.add_column('users', sa.Column('plan', sa.String(length=16), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_index(op.f('ix_scene_analyses_share_token'), table_name='scene_analyses')
    op.drop_column('scene_analyses', 'share_token')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
